export enum SOSStatus {
  SENT = 'SENT',
  FAILED = 'FAILED',
  DELIVERED = 'DELIVERED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
}

export enum WellnessStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
}

export enum NotificationType {
  PERIOD_REMINDER = 'PERIOD_REMINDER',
  MEDICATION_REMINDER = 'MEDICATION_REMINDER',
  SOS_CONFIRMATION = 'SOS_CONFIRMATION',
  HEALTH_REMINDER = 'HEALTH_REMINDER',
}
